--- #YAML:1.0
name:               Ext-Omegle
version:            0.01
abstract:           Perl interface to omegle.com
author:
    - Russell Bradford <russell@rbradford.me>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Async:          
    HTTP::Request::Common:  
    JSON:                 
    WWW::Mechanize:       
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
